language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang++
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-7
    - libboost-dev
before_install: cd parser
install:
  - if [ [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CXX" == "g++" ] ]; then export CXX="g++-4.9"; fi
before_script:
    - uname -a
    - printenv
    - which clang++
    - clang++ --version 2>&1 | grep clang
    - which g++
    - g++ --version
    - $CXX --version
    - cmake --version
script: make --keep-going
notifications:
  email:
    recipients: yuriy.solodkyy+travis.cou@gmail.com
    on_success: change
    on_failure: always
