language: cpp
os:
  - linux
  - osx
compiler:
  - g++
  - clang++
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.8
    - libboost-dev
before_install: cd parser
install:
  - if [[ "$CXX" == g++ ]]; then export CXX="g++-4.8"; fi
before_script:
    - uname -a
    - printenv
    - which clang++
    - clang++ --version 2>&1 | grep clang
script: make --keep-going
notifications:
  email:
    recipients: yuriy.solodkyy+travis.cou@gmail.com
    on_success: change
    on_failure: always
